import type { Player } from '@/lib/data-service'

export const MOCK_PLAYERS: Player[] = [
  {
    id: '1',
    num: 1,
    name: 'Karim',
    full_name: 'Karim Hassan',
    position: 'GK',
    category: 'GK',
    age: 28,
    hometown: 'Dhaka',
    foot: 'Right',
    goals: 0,
    assists: 0,
    image_url: 'https://images.unsplash.com/photo-1552108777-cd4628902c4d?w=400&h=500&fit=crop',
    status: 'Active',
    bio: 'Experienced goalkeeper with excellent reflexes and leadership skills.',
    clean_sheets: 8,
    appearances: 15,
    minutes_played: 1350,
    pass_accuracy: 65,
    chances_created: 0,
    pace: 70,
    shooting: 40,
    passing: 60,
    dribbling: 35,
    defending: 85,
    physical: 80,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    num: 17,
    name: 'Shekhor',
    full_name: 'Shekhor Rahman',
    position: 'DEF',
    category: 'DEF',
    age: 26,
    hometown: 'Chittagong',
    foot: 'Left',
    goals: 1,
    assists: 2,
    image_url: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=400&h=500&fit=crop',
    status: 'Active',
    bio: 'Solid defender with great positioning and strong tackling ability.',
    clean_sheets: 6,
    appearances: 14,
    minutes_played: 1260,
    pass_accuracy: 78,
    chances_created: 2,
    tackles: 45,
    interceptions: 28,
    yellow_cards: 2,
    pace: 75,
    shooting: 50,
    passing: 72,
    dribbling: 60,
    defending: 82,
    physical: 78,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    num: 7,
    name: 'Ahmed',
    full_name: 'Ahmed Hossain',
    position: 'MID',
    category: 'MID',
    age: 25,
    hometown: 'Sylhet',
    foot: 'Right',
    goals: 3,
    assists: 5,
    image_url: 'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=400&h=500&fit=crop',
    status: 'Active',
    bio: 'Creative midfielder with excellent vision and passing range.',
    clean_sheets: 0,
    appearances: 16,
    minutes_played: 1440,
    pass_accuracy: 85,
    chances_created: 12,
    pace: 80,
    shooting: 72,
    passing: 88,
    dribbling: 80,
    defending: 65,
    physical: 75,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    num: 9,
    name: 'Rashed',
    full_name: 'Rashed Ali Khan',
    position: 'FWD',
    category: 'FWD',
    age: 23,
    hometown: 'Rajshahi',
    foot: 'Right',
    goals: 8,
    assists: 3,
    image_url: 'https://images.unsplash.com/photo-1529887893015-bc4ead6c595c?w=400&h=500&fit=crop',
    status: 'Active',
    bio: 'Talented striker with clinical finishing and good movement in the box.',
    clean_sheets: 0,
    appearances: 15,
    minutes_played: 1080,
    pass_accuracy: 72,
    chances_created: 6,
    pace: 88,
    shooting: 86,
    passing: 75,
    dribbling: 82,
    defending: 45,
    physical: 80,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
